### ISSUE TITLE
Hinting changes with ttfautohint

### ISSUE THREAD

**Issue by chrissimpkins** [googlei18n/fontdiff#26]
Does this tool display differences in TrueType instruction set writes to *.ttf files with ttfautohint?  If these changes in shape are not diff'd by default, is there a way to activate this through the tool?  If not possible, then this is a feature request to support this if possible.  It would be very useful to us to be able to view and diff unhinted and hinted renders across build versions.

Thanks!

**Comment by anthrotype** [comment]
the font is loaded in freetype with hinting disabled, and it doesn't seem to be an option to enable that yet.
There's nothing special about ttfautohint as far as hinting is concerned. Let's close this one and continue discussion in the other #23 hinting-related issue.

**Comment by chrissimpkins** [comment]
OK, ty.
