### ISSUE TITLE
Can I change the button image?

### ISSUE THREAD

**Issue by KangheeZi** [googlei18n/fontdiff#27]
Hello I'm a college student who is interested in this project.
I was thinking of changing the button image while looking at this site.
Please see the button image and code I made and reply.

image link : 
https://postfiles.pstatic.net/MjAxODA1MjhfMjg2/MDAxNTI3NTA3MjIzMTI4.DHTCus-TvKvQE9jwbFYVaIJcetkekebRlhnm-TS67M4g.9cgwyqrW4_z5mDKDq7JxpNaD-1mZ1fhQLiKsEZq3wogg.PNG.20gmlwl/SUBMIT_이미지.png?type=w773

<img width="92" alt="image" src="https://user-images.githubusercontent.com/38232494/41188887-7ed720f6-6c00-11e8-8fdd-1d05f9e2005e.png">

source code : 
<html>
	<head>
		<title>Image Button</title>
	</head>
	<body>
	<font style="font: 10pt/15pt larger sans-serif ; font-weight: bold ; font-variant: small-caps ">
<form name="input" action="cgi-bin/select.cgi" method="get">
	"SEARCH THIS SITE: "
	<input type="text" name="xxxx"> 
<input type ="image" src="https://postfiles.pstatic.net/MjAxODA1MjhfMjg2/MDAxNTI3NTA3MjIzMTI4.DHTCus-TvKvQE9jwbFYVaIJcetkekebRlhnm-TS67M4g.9cgwyqrW4_z5mDKDq7JxpNaD-1mZ1fhQLiKsEZq3wogg.PNG.20gmlwl/SUBMIT_이미지.png?type=w773" width="80" height="40"/></form>
<P>
<font style="font: 10pt/15pt larger sans-serif ; font-weight: bold ; font-variant: small-caps ">
<form name="input" action="cgi-bin/imageselect.cgi" method="get">
	"IMAGE SEARCH: "
	<input type="text" name="xxxx">
<input type ="image" src="https://postfiles.pstatic.net/MjAxODA1MjhfMjg2/MDAxNTI3NTA3MjIzMTI4.DHTCus-TvKvQE9jwbFYVaIJcetkekebRlhnm-TS67M4g.9cgwyqrW4_z5mDKDq7JxpNaD-1mZ1fhQLiKsEZq3wogg.PNG.20gmlwl/SUBMIT_이미지.png?type=w773" width="80" height="40"/> </form>
</body>
</html>

**Comment by brawer** [comment]
fontdiff is a command-line tool without user interface, so it has no button.

**Comment by KangheeZi** [comment]
Don’t you want to change your website design?

**Comment by brawer** [comment]
Maybe you mean GitHub’s design... Anyhow, fontdiff has no website so it needs no button.

**Comment by KangheeZi** [comment]
I'm really sorry, but what does this site mean?

http://luc.devroye.org/fonts-86076.html
