### ISSUE TITLE
fontdiff and hb-view rendering differently

### ISSUE THREAD

**Issue by jamesgk** [googlei18n/fontdiff#5]
For the attached fonts, I'm finding that fontdiff and hb-view renderer the string "פרַײ און גלַײך" differently. See attached images:

![hb_before](https://cloud.githubusercontent.com/assets/988758/16504939/74870234-3ecf-11e6-95d5-3077c3da0e43.png)
![hb_after](https://cloud.githubusercontent.com/assets/988758/16504948/7a390ef2-3ecf-11e6-81ae-280116cb7611.png)

![fontdiff](https://cloud.githubusercontent.com/assets/988758/16504957/7e3feb56-3ecf-11e6-84d3-cab76cbbb07e.png)

I'm at a loss as to why this would be, since they both use HarfBuzz. Fonts here:
[NotoSansHebrew-Regular.zip](https://github.com/googlei18n/fontdiff/files/342409/NotoSansHebrew-Regular.zip)

**Comment by jamesgk** [comment]
Ah, I was leaving out the diacritic on that first character, which seems to make all the difference! Probably a false alarm, but I'll investigate this further.

**Comment by dougfelt** [comment]
Monotype says the latest source drop of NotoSansHebrew (June 20) has the
wrong sign for the hhea descender value.  Not sure if that's related or if
that was the font you tested.

**Comment by dougfelt** [comment]
Oh, I see, you're talking about the mark positioning.  There are two places
it is different?

**Comment by jamesgk** [comment]
Yep, the mark positioning and metrics are both different. Though, I think fontdiff will accept differences in metrics so that part should be ok (the ultimate goal being to increase our CI test sample complexity).

**Comment by jamesgk** [comment]
Confirming that this was a user error.

**Comment by brawer** [comment]
Thanks for the confirmation! 👍
