### ISSUE TITLE
Split text into script runs

### ISSUE THREAD

**Issue by brawer** [googlei18n/fontdiff#7]
Currently, fontdiff asks ICU for the most likely script code given the user-supplied BCP47 language tag, and passes this to HarfBuzz. Instead, fontdiff needs to determine script runs. For an example how to do this, see the function [_raqm_resolve_scripts()](https://github.com/HOST-Oman/libraqm/blob/master/src/raqm.c#L1067).

To reproduce, render this snippet with NotoSansCJK.ttc:

```html
<html>
  <div>
    <span lang="ja">今</span>
    <span lang="zh-Hani">今</span>
    <span lang="zh-Hans">今</span>
    <span lang="zh-Hant">今</span>
    <span lang="ko">今</span>
  </div>
</html>
```

Currently, it looks like this:

<img width="286" src="https://cloud.githubusercontent.com/assets/1527880/16970746/a8650002-4e1e-11e6-88c3-820a69919054.png">

The first two letterforms are correct. However, _all_ Chinese letterforms should have the shape of the second glyph, i.e. with a diagonal instead of horizontal stroke in the middle.

**Comment by brawer** [comment]
fontdiff now produces the same shapes with NotoSansCJK as prescribed by the Unicode standard. For example, U+4ECA 今 has a diagonal stroke for language `zh-Hans`, and a horizontal stroke otherwise. Obviously I didn’t test all glyphs, just a few ones. Note that [Wikipedia](https://en.wikipedia.org/wiki/Han_unification#Examples_of_language-dependent_glyphs) is giving different shapes than Unicode, and Unicode is obviously more trustworthy.

![unicode-4eca](https://cloud.githubusercontent.com/assets/1527880/17110596/0a179f16-529e-11e6-92e3-9499c1935061.png)

**Comment by graphicore** [comment]
> Unicode is obviously more trustworthy.

Unicode can be pretty idiosyncratic sometimes. Of course, I have no idea about CJK.
